name=input("Enter a name:")
adjective=input("Enter an adjective:")
verb=input("Enter a verb:")
place=input("Enter a place:")
food=input("Enter a food:")
vehicle=input("Enter a vehicle:")
print(name, adjective, verb, place, food, vehicle)
